### ISSUE TITLE
Diğer Tarayıcılar için Javascript Bookmarklet

### ISSUE THREAD

**Issue by fatihturan** [SalyangozMe/feedback#11]
Chrome haricindeki tarayıcılar için en azından Javascript ile bir bookmarklet yapabilir misiniz? 

Chrome dışında bir tarayıcı kullanınca, eklentisiz paylaşım yapmak imkansız gibi bir şey. :)

**Comment by ademilter** [comment]
geridönüş için teşekkürler @fatihturan,
firefox ve safari için eklentiler yazılıyor. aynı zamanda mobil paylaşımları kolay olması için o kısım içinde birşeyler yapıyoruz yakında yayınlanacak.
