### ISSUE TITLE
Shared links count & Shared before uyarısı

### ISSUE THREAD

**Issue by aoozdemir** [SalyangozMe/feedback#13]
İlk denediğimde aynı linki iki kez paylaşınca count'da iki kez sayılıyor, bir tane gözüküyordu. Linki sildiğinizde ekstradan bir linkiniz oluyordu. Şu an tekrar denedim. Problemsiz güncelleniyor ama bir önceki denememden bir şeyler kalmış olmalı ki, ekstradan bir linkim var şu an gözükmeyen. :smile:

Extension'a aynı linkin daha önce paylaşılıp paylaşılmadığına dair kontrol eklenebilir, linkler çoğaldıkça kontrol etmek zorlaşacak diye düşünüyorum.   

Bir de rails backend'e katkıda bulunmak isterim. Minimal anlamda açık kaynak yapmayı düşünüyor musunuz?

**Comment by askn** [comment]
Merhabalar @aoozdemir,
24 saat içinde aynı linki sadece 1 kez paylaşabiliyorsun. Ekstradan 1 link ise sayının global gösterilenin ise sadece 24 saatlik linkler olmasından kaynaklı bir kafa karışıklığı galiba.

**Comment by aoozdemir** [comment]
Anladım. Bookmarklarken uyarı verilse fena olmaz aslında. :bulb: 

Peki 24 saat+ süre sonrasında tekrar paylaşıldığında eski link tarihi güncelleniyor mu yoksa yeni bir record mu oluşturuyor?

**Comment by askn** [comment]
Yeni 1 kayıt oluşuyor artık farklı bir link bizim için.
Uyarı içinse cc: @ademilter
