### ISSUE TITLE
Popular users

### ISSUE THREAD

**Issue by rwxdash** [SalyangozMe/feedback#15]
Anasayfada, sidebara aktif kullanıcılar, son kullanıcılar, random kullanıcılar vs (herhangi biri, takip edilesiler şeklinde) bir liste eklenebilir diğer kullanıcılara kolay erişim adına. Ve kullanıcıların avatarları üzerinden hover ile kolayca takip edilebilir. Profile gidip takip edip geri dönmek biraz yorucu bir akış diye düşünüyorum.

**Comment by ademilter** [comment]
geri bildirim için teşekkürler;
profile-card olayını aktif edeceğiz. ama sidebar olayı henüz planlarımız arasında yok
