### ISSUE TITLE
Center the main content visually

### ISSUE THREAD

**Issue by gokmen** [SalyangozMe/feedback#16]
In the main feed content not looking centered correctly. It's better to keep the main feed centered and move the heads on the left out of the view.

Before:
![image](https://cloud.githubusercontent.com/assets/42368/15906654/a6f305be-2d6e-11e6-8326-48e3813e492d.png)

After:
![image](https://cloud.githubusercontent.com/assets/42368/15906794/4281ef5e-2d6f-11e6-82b4-0855c8dbfbb8.png)

**Comment by ademilter** [comment]
@gokmen It will be finished in 10 minutes
