### ISSUE TITLE
Beğenilen Linkleri Kayıt Etme

### ISSUE THREAD

**Issue by batuhangoksu** [SalyangozMe/feedback#17]
Beğendiğimiz ve daha sonra erişmek istediğimiz linkleri kayıt edebilmeliyiz bence profilimiz altında kategorize ederek tutabilmeliyiz. Böylece link arşivimizi yapabilir istediğimiz zaman istediğimize tekrar eğişim sağlayabiliriz.

**Comment by ademilter** [comment]
geri bildirim için teşekkürler;
planlarımız arasında yok bu malesef. bunun için pocket, raindrop tarzı uygulamalar kullanmanı öneririm
