### ISSUE TITLE
IFTTT ile Senkronizasyon

### ISSUE THREAD

**Issue by fatihturan** [SalyangozMe/feedback#18]
Selam,

Hiçbir eklentisiz Salyangoz'u kullanmak için IFTTT kanalı oluştursanız ve bizde Twitter'da veya diğer sosyal medya sitelerinde beğendiğimiz ya da favorilere eklediklerimiz şeyleri otomatik olarak Salyangoz'da paylaşılsa sizce nasıl olur?

Bu arada Quora'da IFTTT kanalı nasıl oluşturulacağına dair bir yazı bulmuştum. Yeri gelmişken paylaşayım: https://www.quora.com/How-can-I-create-a-new-IFTTT-channel-to-work-with-my-Internet-Of-Things-product/answer/Bjørn-Rosell

**Comment by ademilter** [comment]
Fatih selam,
Bunu producthunt'da da istediler ve çok mantıklı bir adım olacaktır. Bunun için kolları sıvadık gelişmelere göre haber vereceğim 👍
