### ISSUE TITLE
on Safari (Mac) still asks for Chrome extension to install

### ISSUE THREAD

**Issue by vigo** [SalyangozMe/feedback#19]
![Safari screenshot](https://infinit.io/_/8EsYfDY.png)

If you check closely, already installed Safari Extension :)))

**Comment by ademilter** [comment]
fixed 👍 
<img width="601" alt="screen shot 2016-06-11 at 12 53 45" src="https://cloud.githubusercontent.com/assets/187922/15984446/b7bc2896-2fd3-11e6-9331-5f9515f1df9c.png">
