### ISSUE TITLE
Google Chrome Extension Bildirim

### ISSUE THREAD

**Issue by MuhammetDilmac** [SalyangozMe/feedback#20]
Merhaba,
Takip ettiğimiz kişiler tarafından yapılan son paylaşımları yanda bildirim olarak alsak bence hoş olabilir :) Tabi bu ayarlar kısmından isteyen kişinin açabileceği bir yapıda olmalı :)

**Comment by ademilter** [comment]
Merhaba Muhammet,
bu özellik şuan yapılıyor. yakınd aktif olacak 👍

**Comment by f** [comment]
Bu geliştirme yapıldı. 

![](https://dl.dropbox.com/s/rthjmbiy8svhvjw/Screenshot%202016-06-23%2002.03.49.png?dl=0)
