### ISSUE TITLE
Install Extension to Share bar is always visible

### ISSUE THREAD

**Issue by ugumu** [SalyangozMe/feedback#21]
This bar should only be visible to those who haven't installed the extension yet. It is annoying to see it on every page. 

![screen shot 2016-06-12 at 18 54 23](https://cloud.githubusercontent.com/assets/10109725/15992563/6eb2493a-30cf-11e6-9bbe-92d6856d2caa.png)

**Comment by f** [comment]
Please upgrade extension to 0.0.7

**Comment by ugumu** [comment]
Thanks. You may consider showing an "update your extension" notification next time an update is required.
