### ISSUE TITLE
Tümünü Okundu Olarak İşaretleyebilme

### ISSUE THREAD

**Issue by batuhangoksu** [SalyangozMe/feedback#24]
Merhaba,

Bazen herhangi bir profil tarafından paylaşılan tüm linkleri es geçebiliyorum ilgimi çekmediği için ancak duvarımda sürekli duruyor. Bu sebeple hepsini tek tek bakıldı olarak işaretleyip kaldırmaktansa profil resminin yanında veya başka şekilde tümünü işaretle şeklinde bir düğme olması gerektiğini düşünüyorum.

**Comment by aoozdemir** [comment]
Şurada https://github.com/SalyangozMe/feedback/issues/7#issuecomment-224710380 bahsetmiştim. Github'ın kendi notification sisteminde olduğu gibi, bir kullanıcıya ait tüm linkleri veya feeddeki tüm linkleri okundu olarak işaretleyebilmeliyiz.

**Comment by ademilter** [comment]
bu özelik yeni arayüzle beraber gelecek, şimdilik idare edin lütfen

**Comment by ademilter** [comment]
@batuhangoksu @aoozdemir en çok beklenen özellik geldi sonunda :) keyfini çıkarın 👍

**Comment by batuhangoksu** [comment]
oo alırım bir dal ozaman
