### ISSUE TITLE
Google Chrome Extension Paylaşma Öncesi Düzenleme

### ISSUE THREAD

**Issue by MuhammetDilmac** [SalyangozMe/feedback#25]
Merhabalar,
Google Chrome Extension'da paylaşa tıklanınca önce bir düzenleme alanı gelmeli bence bu alanda varsayılan değerler olmalı fakat kişi isterse bu alanları düzenleyebilmeli bence :) Ayrıca yanlışlıkla tıklayanlar içinde ikinci bir onay olacağı için iyi olabilir :)

**Comment by ademilter** [comment]
geri bildirim için teşekkürler @MuhammetDilmac 
böyle bir kontrol ekleme işlemini uzatacaktır. biz olabildiğince basit olmasını istiyoruz.
ve custom bilgi girme kısmı çok sakıncalı olacaktır. moderasyon gerektirecek işlerden kaçınıyoruz. suistimal olabilecek konular bunlar.
