### ISSUE TITLE
Sign-in Durumunu Koruyamama

### ISSUE THREAD

**Issue by mertsimsek** [SalyangozMe/feedback#26]
Her tarayıcıyı yeniden açışımda login durumum kayboluyor ve tekrar login olmamı istiyor. OSx ve Chrome kullanıyorum. Ayrıca Twitter'da da iki aşamalı (sms doğrulama) giriş sistemi kullanıyorum belki bununla ilgili olabilir :)

**Comment by ademilter** [comment]
login işlemiyle alakalı neredeyse hiç bir işlem yapmıyoruz. twitter'dan en basit bilgileri alıp özellikle kullanıcı adını direkt kayıt yapıp gerisini tarayıcıya bırakıyoruz.
session bilgilerini tarayıcı açık kaldıgı sürece hatırlayabiliyor. tarayıcıyı kapattıgında (quit) bilgilerin silinir tekrar giriş yapman gerekir
