### ISSUE TITLE
new: empty state

### ISSUE THREAD

**Issue by ademilter** [SalyangozMe/feedback#3]
http://emptystat.es/

**Comment by emrecamasuvi** [comment]
hacı abi :) kendine ilham için mi yazdın, yoksa app'e twitter login olunca; empty state ile karşılaşıyorsun. onun için mi yazdın? :) ben o durum için yazacaktım. FYI

**Comment by ekremelmas** [comment]
empty state lazım yazmaya gelmiştim ki kendine not almışsın zaten :) boş home ekranında en çok paylaşım yapan kişileri takip etmeye yönlendirsen kafi

**Comment by ugumu** [comment]
Empty state'te yeni linklerin nasil eklenebilecegine dair bi bilgi olsa fena olmaz. 10 dakikadir sitede link ekle butonu ariyorum :)
