### ISSUE TITLE
Kişi Resminin Üzerine Gelince Bilgilerinin Gözükmesi

### ISSUE THREAD

**Issue by baransomakli** [SalyangozMe/feedback#45]
Recent kısmında paylaşım yapan kişilerin profil resimlerinin üzerine gelince Twitter'daki gibi ad, soyad ya da kullanıcı adı gibi bilgileri görebilirsek daha iyi olabilir.

**Comment by ademilter** [comment]
geri bildirim için teşekkürler @baransomakli 
bu özellik geldi, tadını çıkar 👍

**Comment by baransomakli** [comment]
Süper çok teşekkürler :)
