### ISSUE TITLE
Shortcut for sharing

### ISSUE THREAD

**Issue by aoozdemir** [SalyangozMe/feedback#49]
Paylaşım için extensionlara kısayol eklense tatlı olur. :candy: 

İlk önerim - bir şeyle çakışmıyorsa - `alt + s` :thought_balloon:

**Comment by f** [comment]
Zaten mevcut:

![](https://dl.dropboxusercontent.com/s/c37z4lce6i7sb63/Screenshot%202016-06-20%2009.50.49.png?dl=0)

**Comment by aoozdemir** [comment]
Nasıl kaçırdım :scream: Teşekkür ederim.
