### ISSUE TITLE
Is SalyangozMe dead?

### ISSUE THREAD

**Issue by erkanyildiz** [SalyangozMe/feedback#55]
http://salyangoz.me/ is not working. 
It's been months, I think.
Is this project dead?

**Comment by f** [comment]
Yes we closed it.

5 May 2017 Cum 22:24 tarihinde Erkan YILDIZ <notifications@github.com> şunu
yazdı:

**Comment by erkanyildiz** [comment]
Sorry to hear that. It had a potential. 
Thanks for all your efforts so far.
