### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by aokocax** [SalyangozMe/feedback#6]
http://www.bbc.com/news/technology-36397835 bu siteye girdim, extension iconuna bastım birkaç saniyeliğine progress bar gözüktü ama hiçbir şey olmadı.

**Comment by burakbudak** [comment]
Bende aynı feedback'i ekleyecektim ama sonra sitede "recent" e bakınca eklediğim linkin eklendiğini gördüm. Bu konuda şöyle 2 tavsiyem olabilir. 

1- Ekleme işlemi başarılı olunca o progress bar farklı bir renk olabilir veya ortasında "done" gibi bir şey yazabilir, mavi tik gelebilir vs... 

2- Sayfaya ilk girdiğimde "recent" default gelmeli bence çünkü son eklenenleri görmek öncelik ve sonra dilersem popüler vs görebilirim. Anladığım kadarıyla "new" o amaçla yapıldı ama şu anda öyle çalışmıyor. 

Eklenti oldukça başarılı ve bence producthunt.com sevenler bunu da beğenecektir.

**Comment by emrecamasuvi** [comment]
- progressbarı settimeout ile mi verdiniz, biz öyle bir dark pattern kullanmıştık :) süre biraz daha uzatılabilir; tam dolacakken bekliyor.
- bence "recent" linki anasayfa olmalı.

**Comment by cihadturhan** [comment]
Bende de aynı durum var.

Edit: Şimdi koda baktım da, kodda ajax sorgusu atan bir yer yok :)

```javascript
// Open port to Chrome extension.
var port = chrome.extension.connect();

(function (d) {
  if (document.getElementById("Salyangoz-Extension")) {
    // If any other Salyangoz item exists on page, do not run.
    return;
  }

  // Create and append loading bar.
  var salyangozContainer = document.createElement('div');
  //...


    setTimeout(function () {
      document.body.removeChild(salyangozContainer);
    }, 500);

    clearTimeout(delayedShare);
    clearTimeout(animation);
  }


  var delayedShare, animation;

  animation = setTimeout(function () {
    salyangozContainer.classList.add("isSaving");
  }, 20);

  delayedShare = setTimeout(function () {
    port.postMessage({message: "shareWithSalyangoz"});
  }, 2500);


  port.onMessage.addListener(function (msg) {
    if (msg.message === "salyangozIsShared") {
      removeContainer();
    }
  });

})();
```

**Comment by ademilter** [comment]
Teşekkürler geri dönüşler için;
- **Recent** anasayfa oldu (giriş yapmamış kullanıcıya).
- Eklentideki sorunlar giderildi.
