### ISSUE TITLE
Design + improvement

### ISSUE THREAD

**Issue by burakbudak** [SalyangozMe/feedback#7]
![screen shot 2016-05-30 at 00 43 46](https://cloud.githubusercontent.com/assets/962179/15636183/a27e16b6-25ff-11e6-994e-34ab30c2dead.png)
<Your feedback content here>

Profilimde linklerin yan tarafından paylaşıldığı kaynaktan bir ekran veya sitenin logosu, faviconu gibi bir şey eklenebilir. 

Ayrıca linkler kendi kaynaklarındaki popüler tag'lere göre otomatik tag'leme mantığı ile tag'lenebilir ve böylece uzun vadede tagler'e göre aramalar yapılabilir. (Her ne kadar snapchat gibi paylaşım olacağını söylesen de elinizde bu tür tag'li bir içeriğin bulunması uzun vadede fayda sağlar çünkü bir şekilde silinen içerikler sürekli cazibeli olmayacaktır. )

**Comment by ekremelmas** [comment]
bir sayfayı bookmarkladığımızda loading barı dolduktan sonra done ya da added! gibi bir görsel feedback verse iyi olabilir, ilk eklememde loading barı da %100 dolmadığı için hata oldu zannettim.

**Comment by aoozdemir** [comment]
mark as visited butonunun fixed pozisyona sahip olması (en sağa belki, biraz daha renklendirilmiş şekilde) biraz daha kullanışlı olabilir, özellikle mobil kullanımda. bir de mobilde linklerin left margini biraz daha düşürülebilir. hatta ortalansa daha hoş olur diye düşünüyorum.

![screenshot_77](https://cloud.githubusercontent.com/assets/6544741/15909005/14390e30-2dcd-11e6-8ce7-a5f46d66c13d.png)

**Comment by egriboz** [comment]
Favicon url hatası!

https://salyangoz.me/images/meta/favicon.ico
