### ISSUE TITLE
Google Chrome Extensions animasyon önerisi

### ISSUE THREAD

**Issue by haibnu** [SalyangozMe/feedback#8]
Ufak bir önerim var 😊  Salyangozun geride bıraktığı izle loading animasyon olsa?

![recommend](https://cloud.githubusercontent.com/assets/920066/15656532/16e691ac-26b1-11e6-9400-653ed46b59b7.png)

**Comment by f** [comment]
@haibnu https://github.com/SalyangozMe/extensions PR açabilirsin abi :)
